# Generated by Django 5.0.7 on 2024-07-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_offer_services_remove_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='offer',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='service',
            field=models.IntegerField(),
        ),
    ]
