# Generated by Django 5.0.7 on 2024-07-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_alter_offerdetail_offer_alter_offerdetail_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.offer'),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.service'),
        ),
    ]
