# Generated by Django 5.0.7 on 2024-07-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_offerdetail_offer_alter_offerdetail_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='service',
        ),
    ]
